version: "3.8"
services:
  openldap:
    image: osixia/openldap:1.4.0
    container_name: openldap
    command: [--copy-service, --loglevel, debug]
    restart: always
    # read_only: true
    ports:
      - "389:389"
      - "636:636"
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Kubernetes LDAP"
      LDAP_DOMAIN: "${DOMAIN}"
      LDAP_BASE_DN: "${LDAP_BASE_DN}"
      LDAP_ADMIN_PASSWORD: "${LDAP_ADMIN_PASSWORD}"
      LDAP_CONFIG_PASSWORD: "${LDAP_CONFIG_PASSWORD}"
      LDAP_READONLY_USER: "false"
      LDAP_READONLY_USER_USERNAME: "readonly"
      LDAP_READONLY_USER_PASSWORD: "${LDAP_READONLY_USER_PASSWORD}"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.pem"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
      LDAP_TLS_CA_CRT_FILENAME: "ca.pem"
      LDAP_TLS_ENFORCE: "true"
      # LDAP_TLS_ENFORCE: "false"
      # LDAP_TLS_CIPHER_SUITE: "SECURE256:+SECURE128:-VERS-TLS-ALL:+VERS-TLS1.2:-RSA:-DHE-DSS:-CAMELLIA-128-CBC:-CAMELLIA-256-CBC:-VERS-SSL3.0:HIGH:+SSLv3:+TLSv1:MEDIUM:+SSLv2:@STRENGTH:+SHA:+MD5:!NULL"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      # 不要设置成 demand，这个选项可以理解成双向认证，也就是客户端连接ldap时也许要提供证书，也就是客户端也需要有自己的证书
      LDAP_TLS_VERIFY_CLIENT: "allow"
      LDAP_REPLICATION: "false"
      LDAP_REPLICATION_CONFIG_SYNCPROV: "binddn=\"cn=admin,cn=config\" bindmethod=simple credentials=\"${LDAP_CONFIG_PASSWORD}\" searchbase=\"cn=config\" type=refreshAndPersist retry=\"60 +\" timeout=1 starttls=critical"
      LDAP_REPLICATION_DB_SYNCPROV: "binddn=\"cn=admin,${LDAP_BASE_DN}\" bindmethod=simple credentials=\"${LDAP_ADMIN_PASSWORD}\" searchbase=\"${LDAP_BASE_DN}\" type=refreshAndPersist interval=00:00:00:10 retry=\"60 +\" timeout=1 starttls=critical"
      # LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
      LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldaps://${LDAP_DOMAIN}']"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - ./ldap/data:/var/lib/ldap
      - ./ldap/config:/etc/ldap/slapd.d
      - ./cert/ldap.pem:/container/service/slapd/assets/certs/ldap.pem
      - ./cert/ldap.key:/container/service/slapd/assets/certs/ldap.key
      - ./cert/ca.pem:/container/service/slapd/assets/certs/ca.pem
      - /etc/localtime:/etc/localtime:ro
    # important: same as hostname
    domainname: "${LDAP_DOMAIN}"
    hostname: "${LDAP_DOMAIN}"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
        reservations:
          memory: 128M
    networks:
      - ldap

  ldap-account-manager:
    image: ldapaccountmanager/lam:7.4
    container_name: ldapaccountmanager
    # restart: unless-stopped
    restart: always
    ports:
      - "80"
    environment:
      - LDAP_SERVER=${LDAP_SERVER}
      - ADMIN_USER=cn=admin,${LDAP_BASE_DN}
      - LAM_PASSWORD=${LAM_PASSWORD}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - LAM_LANG=en_ZH
      - TZ=Asia/Shanghai
      - DEBUG=true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          memory: 50M
    tty: true
    stdin_open: true
    domainname: "ldapac.${DOMAIN}"
    hostname: "ldapac.${DOMAIN}"
    volumes:
      - lametc/:/etc/ldap-account-manager
      - lamconfig/:/var/lib/ldap-account-manager/config
      - lamsession/:/var/lib/ldap-account-manager/sess
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - openldap
    networks:
      - ldap

  phpldapadmin:
    # image: osixia/phpldapadmin:latest
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    command: [--copy-service, --loglevel, debug]
    # read_only: true
    restart: always
    ports:
      - "443"
    environment:
      # /var/www/phpldapadmin/config/config.php
      # openldap 中开启了LDAP_TLS_ENFORCE，tls 也必须为 true
      # json 格式错误会报错/var/www/phpldapadmin/config/config.php错误
      # PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'${LDAP_DOMAIN}': [{'server': [{'tls': False}]},{'login': [{'bind_id': 'cn=admin,${LDAP_BASE_DN}', 'bind_pass': '${LDAP_ADMIN_PASSWORD}'}]}]}, '${LDAP_DOMAIN}']"
      PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'${LDAP_DOMAIN}': [{'server': [{'tls': True}]},{'login': [{'bind_id': 'cn=admin,${LDAP_BASE_DN}', 'bind_pass': '${LDAP_ADMIN_PASSWORD}'}]}]}, '${LDAP_DOMAIN}']"
      PHPLDAPADMIN_SERVER_ADMIN: "ansandy@foxmail.com"
      PHPLDAPADMIN_SERVER_PATH: "/phpldapadmin"
      # PHPLDAPADMIN_HTTPS: "false"
      PHPLDAPADMIN_HTTPS: "true"
      PHPLDAPADMIN_HTTPS_CRT_FILENAME: "${DOMAIN}.pem"
      PHPLDAPADMIN_HTTPS_KEY_FILENAME: "${DOMAIN}.key"
      PHPLDAPADMIN_HTTPS_CA_CRT_FILENAME: "ca.pem"
      PHPLDAPADMIN_LDAP_CLIENT_TLS: "true"
      PHPLDAPADMIN_LDAP_CLIENT_TLS_REQCERT: "try"
      PHPLDAPADMIN_LDAP_CLIENT_TLS_CRT_FILENAME: "ldap.pem"
      PHPLDAPADMIN_LDAP_CLIENT_TLS_KEY_FILENAME: "ldap.key"
      PHPLDAPADMIN_LDAP_CLIENT_TLS_CA_CRT_FILENAME: "ca.pem"
      PHPLDAPADMIN_TRUST_PROXY_SSL: "true"
      PHPLDAPADMIN_SSL_HELPER_PREFIX: "phpldapadmin"
      LDAP_CLIENT_SSL_HELPER_PREFIX: "ldap"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          memory: 50M
    tty: true
    stdin_open: true
    volumes:
      # config
      # - ./config/my-env.yaml:/container/environment/01-custom/env.yaml
      # - ./config/config.php:/var/www/phpldapadmin/config/config.php
      # https
      - ./https/${DOMAIN}.pem:/container/service/phpldapadmin/assets/apache2/certs/${DOMAIN}.pem
      - ./https/${DOMAIN}.key:/container/service/phpldapadmin/assets/apache2/certs/${DOMAIN}.key
      - ./https/ca.pem:/container/service/phpldapadmin/assets/apache2/certs/ca.pem
      # tls
      - ./cert/ldap.pem:/container/service/ldap-client/assets/certs/ldap.pem
      - ./cert/ldap.key:/container/service/ldap-client/assets/certs/ldap.key
      - ./cert/ca.pem:/container/service/ldap-client/assets/certs/ca.pem
      - /etc/localtime:/etc/localtime:ro
    domainname: "admin.${DOMAIN}"
    hostname: "admin.${DOMAIN}"
    depends_on:
      - openldap
    networks:
      - ldap

  nginx:
    image: nginx:1.18.0
    container_name: nginx
    # command: sleep 365d
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./https/${DOMAIN}.pem:/etc/nginx/ssl/server.pem
      - ./https/${DOMAIN}.key:/etc/nginx/ssl/server.key
      - ./https/ca.pem:/etc/nginx/ssl/ca.pem
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/manager.conf:/etc/nginx/conf.d/manager.conf
      - ./nginx/guide:/usr/share/nginx/guide
    depends_on:
      - openldap
      - ldap-account-manager
    networks:
      - ldap

networks:
  ldap:

volumes:
  lametc:
  lamconfig:
  lamsession:
